### ISSUE TITLE
ImportError: libpython3.3m.so.1.0: cannot open shared object file: No such file or director

### ISSUE THREAD

**Issue by jgirardet** [varp/sublime-psutil#2]
Hi,
importing psutil in a plugin gives me the following.
sublime build 3176
ubuntu 18.04

I do not have python3.3 on my system, except in sublimetext dir.

```
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 116, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 584, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1022, in load_module
  File "<frozen importlib._bootstrap>", line 1003, in load_module
  File "<frozen importlib._bootstrap>", line 560, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 868, in _load_module
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "/home/jimmy/.config/sublime-text-3/Packages/sublack2/sb.py", line 6, in <module>
    from .sublack import *  # noqa
  File "/home/jimmy/.config/sublime-text-3/Packages/sublack2/sublack/__init__.py", line 2, in <module>
    from . import utils
  File "/home/jimmy/.config/sublime-text-3/Packages/sublack2/sublack/utils.py", line 5, in <module>
    import psutil
  File "/home/jimmy/.config/sublime-text-3/Packages/psutil/st3_linux_x64/psutil/__init__.py", line 99, in <module>
    from . import _pslinux as _psplatform
  File "/home/jimmy/.config/sublime-text-3/Packages/psutil/st3_linux_x64/psutil/_pslinux.py", line 26, in <module>
    from . import _psutil_linux as cext
ImportError: libpython3.3m.so.1.0: cannot open shared object file: No such file or directory
```

**Comment by varp** [comment]
I'll check

**Comment by varp** [comment]
Ok! I confirm your issue. As a workaround, you can install python33 on your host, until I'll compile static-linked version.

**Comment by varp** [comment]
Ok! I've made a new release. Please check out.

**Comment by jgirardet** [comment]
thanks
