### ISSUE TITLE
ImportError in 64bit Windows 10

### ISSUE THREAD

**Issue by randy3k** [varp/sublime-psutil#3]
```
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 125, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 584, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1022, in load_module
  File "<frozen importlib._bootstrap>", line 1003, in load_module
  File "<frozen importlib._bootstrap>", line 560, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 868, in _load_module
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "C:\Users\IEUser\AppData\Roaming\Sublime Text 3\Packages\Terminus\main.py", line 28, in <module>
    from .terminus.core import (
  File "C:\Users\IEUser\AppData\Roaming\Sublime Text 3\Packages\Terminus\terminus\core.py", line 14, in <module>
    from .terminal import Terminal, CONTINUATION
  File "C:\Users\IEUser\AppData\Roaming\Sublime Text 3\Packages\Terminus\terminus\terminal.py", line 9, in <module>
    import psutil
  File "C:\Users\IEUser\AppData\Roaming\SUBLIM~1\Packages\psutil\ST3_WI~2\psutil\__init__.py", line 77, in <module>
    from ._common import AIX
ImportError: cannot import name AIX
```

**Comment by randy3k** [comment]
@varp 
I have automated the building process at https://github.com/randy3k/psutil
Ultimately, I wish to move my repo to https://github.com/packagecontrol and replace this repo. How do you feel about it?

**Comment by varp** [comment]
@randy3k Where have you moved you repo?

**Comment by varp** [comment]
Ohh I've just found it!
